name: My Action
description: Action description
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  working-directory:
    description: The working directory where Terraform will be executed
    required: false
  subject:
    description: The subject to greet
    required: false
    default: World

runs:
  using: composite
  steps:
    - name: My Action
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_ACTION_INPUT_subject: ${{ inputs.subject }}
      run: |
        $GITHUB_ACTION_PATH/scripts/main.ps1
