name: Auto-Document

run-name: "Auto-Document - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # Required to push to the branch

jobs:
  Auto-Document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto-Document
        uses: PSModule/Auto-Document@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
