name: Auto-Configure

run-name: "Auto-Configure - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # Required to create releases
  pull-requests: write # Required to create comments on the PRs

jobs:
  Auto-Configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto-Configure
        uses: PSModule/Auto-Configure@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
